---
title: "Class notes"
output: html_document
date: "2022-09-13"
---

```{r}
Y <- 3.6
Z <- "myvariable"
#H <- myvariable # don't forget to use quotes when you work with string variables
typeof(Y)
typeof(Z)
```

```{r}
X <- c(1,2,3,4)
X
seq(1,4,1) # start, end, increments
1:4 # whole numbers from 1 through 4, (4 included)
length(X)

seq(1,10,length.out=10)

rep(3,5)
rep("mytext",5)
rep(1:3,5)
rep(c(1,2,3),5)
```

```{r}
names(X) <- c("firstelement","secondelement","thirdelement","fourthelement")
X
```


```{r}
names(X)[3] <- "THIRDELEMENT"
X
```


```{r}
X <- matrix(1:10,nrow=2,byrow = T)
X
length(X) # returns the length of matrix (treating X as a one dimensional vector)
dim(X) # returns the dimensions of the matrix

X[2,2]
X[2,5]
X[1,3]
X[2,] # returns the second row
X[,5] # returns the fifth column
X
X[, c(2,4)]
X
X[, -c(2,4)]
```

```{r}
rownames(X) <- c("firstrow","secondrow")
colnames(X) <- c("col1","col2","col3","col4","col5")
X
dimnames(X) # returns a list with two elements, rownames and colnames
```

```{r}
mylist <- list(rep(2,3), matrix(1:4,nrow=2,byrow=T),c("hello","bye"))
names(mylist) <- c("firstlement","secondelement","thirdelement")
mylist$firstlement
mylist
```
```{r}
# Categorical data, aka Factor variables
Treatment <- c("Drug","Drug","Drug","Placebo","Placebo","Placebo")
Treatment <- factor(Treatment) # declares that vector Treatment is categorical data
Treatment
print.default(Treatment)
```

```{r}
myclass <- c("Upper","Upper","Lower","Middle","Middle")
ordered(myclass,levels=c("Upper","Middle","Lower")) # to change the order (1st<2nd<3rd)
```

```{r}
#### 9/15/2022
# make sure to give vectors with the same length!
df <- data.frame(Number=c(1,4,2,5),Letter=c("a","r","g","f"),Truth=c(T,F,F,T))
df
```
```{r}
#df[2,] # returns the second row using position
#df[,2] # returns the second column position
df$Letter
```

```{r}
#df[3,1] # returns row 3, col 1
#df$Number[3] # returns element pos 3 in column "Number"
#df[,2]
df[,"Letter"]
```

```{r}
ncol(df) # three columns in df
nrow(df) # four rows in df
```

```{r}
Y <- matrix(1:10000,nrow=1000,byrow=T)
head(Y)
```

```{r}
# we want a function that prints "Hello World!" when it's called
say_hi = function(){
  
  print("Hello World!")
  
}
```

```{r}
#fix(say_hi) # displays the contents of the function
```

```{r}
say_hi()
```

```{r}
myfunc = function(myinput){
  
  return(myinput*2)
  
}
```

```{r}
myfunc(20)
```


```{r}
x <- 2

if(x<0){
  print("This number is negative!")
} else { 
  print("This number is non-negative!")
}
```


```{r}
x <- 0

if(x<0){
  print("This number is negative!")
} else if(x==0){
  print("This number is zero!")
} else {
  print("This number is positive!")
}
```

```{r}
evenorodd = function(num){
  if(num %% 2 == 0){
    return("This is an even number!")
  } else{
    return("This is an odd number!")
  }
}
```

```{r}
evenorodd(10)
```

```{r}
# a for loop that prints numbers 1 through 3
for(i in 1:3){
  print(i)
}
```
```{r}
myvector <- c('a', 'vector','of','character','values','works','too!')
for(i in myvector){
  print(i)
}
```

```{r}
myvector <- c('a', 'vector','of','character','values','works','too!')
for(i in myvector){
  print(i)
  # browser() in case you want to stop at an iteration for debugging, 'n': next line; 'c' continue; 'Q' quit debugging.
}
```

```{r}
#install.packages("MASS") # just run this for the first time
library(MASS)
data("Cars93")
Cars93
```



